[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#131B2A"
textColor = "#E2E8F0"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
